blog/urls.py
from django.urls import path, re_path

from blog.views import index, upload, article, comment, account, reptile, vedio, leave_messge, topic


app_name = 'blog'

urlpatterns = [
    path('', index.index, name='index'),
    path('upload/', upload.upload, name='upload'),
]

# Links about article
urlpatterns += [
    path('detail/<int:article_id>/', article.get_article_by_id, name='article-detail'),
    re_path(r'^articles/(?:page/(?P<page>\d+)/)?$', article.lists, name='articles-list'),
    re_path(r'^articles/tag/(?P<tag>\w+)/(?:page/(?P<page>\d+)/)?$', article.get_articles_by_tag, name='articles-tag'),
    re_path(r'^articles/(?P<cate>\w+)/(?:page/(?P<page>\d+)/)?$', article.get_articles_by_category, name='articles-cate'),
    path('comment/appreciate/', comment.comment_appreciate, name='comment-appreciate'),
    path('comment/dislike/', comment.comment_dislike, name='comment-dislike'),
    path('reply/dislike/', comment.reply_dislike, name='reply-dislike'),
    path('reply/appreciate/', comment.reply_appreciate, name='reply-appreciate'),
    path('reply/', comment.reply, name='article-comment'),
    path('comment/', comment.comment, name='article-comment'),
    path('comment/load_more/', comment.load_comments, name='comment-loadmore'),
]

# Links about account
urlpatterns += [
    path('user/login/', account.do_login, name='user-login'),
    path('user/logout/', account.do_logout, name='user-logout'),
    path('user/register/', account.register, name='user-register'),
    path('user/edit/', account.edit, name='user-edit'),
    path('user/do-edit/', account.do_edit, name='user-do-edit'),
    path('user/check-username/', account.check_username, name='user-check-username'),
    path('user/check-email/', account.check_email, name='user-check-email'),
    path('user/forget-password/', account.forget_password, name='user-forget-password'),
    path('user/captcha/', account.gen_captcha, name='user-gen-captcha'),
]

# Others Lnks
urlpatterns += [
    path('message/', leave_messge.leave_message, name='message-leave'),
    path('reptiles/', reptile.lists, name='reptiles-lists'),
    path('videos/', vedio.lists, name='videos-lists'),
    path('topics/', topic.lists, name='topics'),
]


blog/views/account.py
import base64
import os
import re
import uuid
from functools import partial

from PIL import Image
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.cache import cache
from django.core.files.base import ContentFile
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.utils import timezone
from django.views.decorators.http import require_GET, require_POST

from blog.models import UserInfo, Job
from blog.utils.http import (JsonSuccessResponse,
                             JsonFailResponse)
from blog.utils.thread_email import send_mail
from blog.views import captcha
from blogproject import settings

send_forget_password_mail = partial(send_mail, '密码找回邮件确认', '', '1147883997@qq.com')

EMAIL_PATTERN = r'^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,})$'


@require_POST
def do_login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    if not username or not password:
        return JsonFailResponse('username or password is null')

    user = User.objects.filter(Q(username=username) | Q(email=username)).first()
    if not user or not user.check_password(password):
        return JsonFailResponse('username or password is wrong')

    login(request, user)
    return JsonSuccessResponse('login success')


@require_POST
def register(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    if not username or not password:
        return JsonFailResponse('username or password is null')

    try:
        user = User.objects.create_user(request.POST['username'], '', request.POST['password'])
        user.save()
    except Exception as e:
        print(e)
        return JsonFailResponse('create user failed')
    else:
        user_info = UserInfo()
        user_info.user = user
        user_info.save()
        login(request, user)

    return JsonSuccessResponse('register success')


def is_login(request):
    return not request.user.is_anonymous


@login_required
def do_logout(request):
    logout(request)
    return HttpResponseRedirect('/blog/articles/')


@login_required
def edit(request):
    return render(request, 'blog/account/profile_edit.html')


@require_POST
@login_required
def do_edit(request):
    nickname = request.POST.get('nickname')
    email = request.POST.get('email')
    signature = request.POST.get('signature')
    gender = request.POST.get('gender')
    job = request.POST.get('job')
    education = request.POST.get('education')
    f_avatar = request.FILES.get('avatar')

    user_info = request.user.userinfo or UserInfo()
    if not nickname or len(nickname) > 50:
        return JsonFailResponse('username is null or too long')
    user_info.nickname = nickname

    if not email or not re.match(EMAIL_PATTERN, email) or email_exists(request):
        return JsonFailResponse('invalid email')
    request.user.email = email

    if signature:
        user_info.signature = signature

    if gender:
        if int(gender) in [i[0] for i in UserInfo.GENDER_CHOICES]:
            user_info.gender = gender
        else:
            return JsonFailResponse('invalid gender')

    if job:
        user_info.job = Job.objects.get(id=job)

    if education:
        user_info.education = education

    if f_avatar:
        ext = os.path.splitext(f_avatar.name)[1]
        if ext not in UserInfo.AVATAR_EXT_LIMITS:
            return JsonFailResponse(f'unsupported ext {ext}')

        if f_avatar.size > UserInfo.AVATAR_SIZE_LIMIT:
            return JsonFailResponse(f'image size is too big')

        f_avatar_con = ContentFile(f_avatar.read())
        f_avatar_name = request.user.username + ext
        user_info.avatar.save(f_avatar_name, f_avatar_con, save=False)

        img = Image.open(os.path.join(settings.MEDIA_ROOT, 'upload', 'images', 'avatar', f_avatar_name))
        out = img.resize(UserInfo.AVATAR_SIZE_DEFAULT, resample=Image.ANTIALIAS)
        out.save(f_avatar_name)

    user_info.save()

    return JsonSuccessResponse('edit success')


def email_exists(request):
    email = request.GET.get('email')
    user = User.objects.filter(email=email).first()
    return user and (request.user.is_authenticated or request.user != user)


@require_GET
def check_username(request):
    username = request.GET.get('username')
    user = User.objects.filter(username=username).first()
    return JsonResponse({'valid': user is None or user == request.user})


@require_GET
def check_email(request):
    return JsonResponse({'valid': not email_exists(request)})


@require_GET
def gen_captcha(request):
    data, code = captcha.draw(font_size=40)
    request.session['{sessionid}_captcha'.format(sessionid=request.COOKIES.get('sessionid'))] = code.upper()
    return HttpResponse(data)


@require_POST
def forget_password(request):
    email = request.POST.get('email')
    captcha_ = request.POST.get('captcha')
    sessionid = request.COOKIES.get('sessionid')
    session_captcha = request.session.get(f'{sessionid}_captcha')

    if not email or not captcha_:
        return JsonFailResponse('email or captcha is null')

    if captcha_.upper() != session_captcha:
        return JsonFailResponse('invalid captcha')

    try:
        send_forget_password_mail(
            [email],
            html_message="""
                Dear JoyBlog user! <br><br><br>
                When you visit JoyBlog, you click the "forget password" link, which is a password reset confirmation message. <br><br>
                You can reset the account password by clicking the following link: <br><br>
                <a href= "target=" target= "_blank" > click on the link to retrieve the password<br>
                To keep your account safe, click on the link within 10 minutes, or you can copy the link to the browser's address bar. <br>
                If you have not tried to modify the password, please ignore this email, and this will inconvenience you. <br><br><br>
                This email is automatically sent by the system, please do not reply directly.
                """
        )
    except BaseException as e:
        print(e)
        return JsonFailResponse('email send failed')
    else:
        key = f'forget_password:{email}'
        value = {
            'uuid_str': base64.b64encode(uuid.uuid4().hex.encode('utf-8')),
            'link_id': base64.b64encode(str(timezone.now().timestamp()).encode('utf-8'))
        }
        cache.set(key, value, timeout=60 * 10)
        return JsonSuccessResponse('email send success')

blog/views/article.py
import re

import jieba
import jieba.analyse
from django.core.cache import cache
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render
from django.views.decorators.http import require_GET

from blog.models import Article
from blog.utils.MyPaginator import MyPaginator

page_size = 10
page_width = 5


# 文章列表查询
@require_GET
def lists(request, page):
    key = request.GET.get('key')
    page = page or 1
    if key:
        return get_articles_by_key(request, page)
    else:
        articles = Article.objects.only('id', 'title', 'summary', 'picture', 'creationTime').all().order_by('-viewTime')
        p = MyPaginator(articles, page_size)
        articles = p.get_my_page(page, page_width)
        return render(request, 'blog/article/index.html', {'articles': articles})


# Article falls
@require_GET
def falls(request):
    page_num = request.GET.get('page', 1)
    page_num = page_num if page_num > 0 else 1
    articles = Article.objects.order_by('-creationTime')
    p = Paginator(articles)
    page = p.get_page(page_num)
    return render(request, 'blog/includes/falls.html', {'articles': page})


# 通过文章id获取文章详情
def get_article_by_id(request, article_id):

    article = Article.objects.filter(id=article_id).first()
    if article:

        comments = article.comment_set.all()
        comment_size = comments.count()
        reply_size = 0
        for comment in comments:
            reply_size += comment.replies.all().count()

        key = 'lock:%s:%s' % ('article', article_id)
        with cache.lock(key):
            article.viewTime += 1
            if article.viewTime > 100:
                article.recommend = True
            article.save(update_fields=['viewTime', 'recommend'])

    else:
        return None

    context = {'article': article,
               'total_num': comment_size + reply_size, 'inclusion_tag': article.tags.all()}

    return render(request, 'blog/article/detail.html', context)


# 根据标签编号查询文章
def get_articles_by_tag(request, tag, page=1):
    articles = Article.objects.filter(tags__code=tag).order_by('-viewTime')
    p = MyPaginator(articles, page_size)
    articles = p.get_my_page(page, page_width)
    return render(request, 'blog/article/index.html', {'articles': articles, 'tag': tag})


# 根据类别查询文章
def get_articles_by_category(request, cate, page=1):
    articles = Article.objects.filter(category__code=cate).order_by('-viewTime')
    p = MyPaginator(articles, page_size)
    articles = p.get_my_page(page, page_width)
    return render(request, 'blog/article/index.html', {'articles': articles, 'cate': cate})


# 根据关键词查询并分页
def get_articles_by_key(request, page):

    key = request.GET['key']

    seg_list = jieba.lcut_for_search(key, HMM=False)
    seg_list = [x for x in set(seg_list) if len(x) > 1 and re.match('[\u4e00-\u9fa5A-Za-z0-9]', x)]
    seg_list = seg_list or [key]

    query = None
    select_params_list = []
    select_dict = dict()
    order_by_title_list = []
    order_by_summary_list = []

    def contains(seg):
        return Q(title__contains=seg) | Q(summary__contains=seg)

    def title_alias(seg):
        return 'is_title_like_%s' % seg

    def summary_alias(seg):
        return 'is_summary_like_%' % seg

    def title_like(seg):
        return 'blog_article.title like %s'

    def summary_like(seg):
        return 'blog_article.summary like %s'

    #select_dict = [{title_alias(seg): title_like(seg), summary_alias(seg)} for seg in seg_list]
    for seg in seg_list:

        query = query | contains(seg) if query else contains(seg)

        title_alias = f'is_title_like_{seg}'
        summary_alias = f'is_summary_like_{seg}'
        select_dict[title_alias] = 'blog_article.title like %s'
        select_dict[summary_alias] = 'blog_article.summary like %s'
        select_params_list.append('%' + seg + '%')
        select_params_list.append('%' + seg + '%')
        order_by_title_list.append('-' + title_alias)
        order_by_summary_list.append('-' + summary_alias)

    articles = Article.objects.filter(query)\
        .only('id', 'title', 'summary', 'creationTime')\
        .extra(select=select_dict, select_params=select_params_list,
               order_by=order_by_title_list + order_by_summary_list).distinct()

    p = MyPaginator(articles, page_size)
    articles = p.get_my_page(page, page_width)

    return render(request, 'blog/article/index.html',
                  {'articles': articles, 'words': seg_list, 'key': key})

blog/views/captcha.py
import random, math
from io import BytesIO
from PIL import Image, ImageDraw, ImageFont


def _random_bg_color():
    """获取随机的背景颜色"""
    return random.randint(50, 250), random.randint(50, 255), random.randint(50, 255)


def _random_font_color():
    """获取随机的字体颜色"""
    return random.randint(200, 255), random.randint(0, 50), random.randint(0, 50)


def _random_line_point_color():
    """生成随机颜色"""
    return random.randint(0, 255), random.randint(10, 255), random.randint(64, 255)


def _random_char():
    """获取随机字符"""
    return random.choice([chr(random.randint(65, 90)), str(random.randint(1, 9)), chr(random.randint(97, 122))])


def _char_pos(index, length, size, font_size):
    """
    获取字符的插入点
    :param index: 字符的下标
    :param length: 验证码长度
    :param size: 验证码图片尺寸(width, height)
    :param font_size: 字体大小
    :return:
    """
    width, height = size
    grid_width = math.ceil(width / length)
    return random.randint(grid_width * index, grid_width * (index+1) - font_size), random.randint(0, height-font_size)


def draw(width=279, height=50, length=6, font_file='AaDongRiGuShi-2.ttf', font_size=30):
    """
    绘制验证码图片
    :param width: 图片宽度
    :param height: 图片高度
    :param length: 字符长度
    :param font_file: 字体文件
    :param font_size: 字体大小
    :return: data图片, code验证码
    """
    f = BytesIO()
    font = ImageFont.truetype('blog/static/blog/webfonts/captcha/' + font_file, font_size)

    img = Image.new(mode='RGB', size=(width, height), color=_random_bg_color())
    draw = ImageDraw.Draw(img, mode='RGB')

    char_list = []

    # 画字
    for i in range(length):
        char = _random_char()
        print('='*20, _char_pos(i, length, (width, height), font_size))
        draw.text(_char_pos(i, length, (width, height), font_size), char, _random_font_color(), font=font)
        char_list.append(char)

    # 写干扰点
    for i in range(40):
        draw.point([random.randint(0, width), random.randint(0, height)], fill=_random_line_point_color())

    # 写干扰圆圈
    for i in range(40):
        draw.point([random.randint(0, width), random.randint(0, height)], fill=_random_line_point_color())
        x = random.randint(0, width)
        y = random.randint(0, height)
        draw.arc((x, y, x + 4, y + 4), 0, 90, fill=_random_line_point_color())

    # 画干扰线
    for i in range(5):
        x1 = random.randint(0, width)
        y1 = random.randint(0, height)
        x2 = random.randint(0, width)
        y2 = random.randint(0, height)
        draw.line((x1, y1, x2, y2), fill=_random_line_point_color())

    img.save(f, "png")
    return f.getvalue(), ''.join(char_list)

blog/views/index.py
from django.contrib.auth.models import User
from django.shortcuts import render


# index page
from blog.apps import BlogConfig
from blog.models import Article


def index(request):
    articles = Article.objects.all()
    author = User.objects.get(username=BlogConfig.author_name)
    return render(request, 'blog/index/index.html', {
        'articles': articles,
        'author': author})

blog/views/leave_messge.py
from blog.models import LeaveMessage
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import json,re


@login_required
def leave_message(request):
    """
    用户留言功能
    :param request:
    :return:
    """
    content = request.POST.get('content', None)
    if content is None:
        return HttpResponse(json.dumps({'status':False, 'message':'留言内容不能为空'}), content_type='application/json')
    elif len(re.sub(r'[^\x00-\xff]', 'aa', content)) > 60:
        return HttpResponse(json.dumps({'status': False, 'message': '留言内容太长'}), content_type='application/json')

    message = LeaveMessage()
    message.content = content
    message.user = request.user
    message.save()

    return HttpResponse(json.dumps({'status':True, 'message':'留言成功'}), content_type='application/json')

blog/views/reptile.py
from django.shortcuts import render

from blog.apps import BlogConfig
from blog.models import Article


def lists(request):
    reptiles = Article.objects.filter(tags__code=BlogConfig.reptile_tag_code).order_by('creationTime')
    return render(request, 'blog/reptile/reptiles.html', {'reptiles': reptiles})

blog/views/vedio.py
from django.shortcuts import render


def lists(request):

    return render(request, 'blog/video.html')

blog/templates/blog/includes/comments.html
{# 对评论列表进行渲染 传入参数num: 总的评论条数, comments: 评论和回复的字典集合 #}

{# Comment Section #}
<div class="container u-space-2">
  <div class="w-lg-60 mx-auto">

    <header class="row justify-content-between align-items-center">
      <div class="col-6">
        <h4 class="h6 mb-0">共{{ total_num }}条评论</h4>
      </div>
{#      <div class="col-6 col-sm-4 col-md-3">#}
{#        <select class="custom-select border-0">#}
{#          <option selected="">排序</option>#}
{#          <option value="comments1">热门评论</option>#}
{#          <option value="comments2">最新评论</option>#}
{#        </select>#}
{#      </div>#}
    </header>


    <hr class="mt-2 mb-6">

    <div class="comments">
            {% for comment_dict in comments %}
                {# Comment Item #}
                    {% include 'blog/includes/comment_item.html' with item=comment_dict %}
                {# End Comment Item #}


            {% endfor %}
    </div>

    <a id="load-more" class="btn btn-block u-btn-primary--air transition-3d-hover" href="javascript:void(0)" data-page="2">加载更多</a>
  </div>
</div>

{# End Comment Section #}

blog/templates/blog/includes/copyright.html
<!-- Logo -->
<a class="d-inline-block mb-4" href="{% url 'blog:index' %}">
    <span class="logo">JOY BLOG</span>
</a>
<!-- End Logo -->
<!-- Copyright -->
<p class="small text-muted mb-0">© Joy. 2018 PythonCommunity. All rights reserved.</p>
<!-- End Copyright -->

blog/templates/blog/includes/falls.html
{% load static %}
{% load smart_timesince %}
{% load special_article_item %}
{% load random_tag_theme %}

<!-- End Item -->
{% for article in articles %}
        {% if forloop.first %}
            <!-- Item -->
            <div class="cbp-item">
            <div class="cbp-caption">
              <!-- Blog Card -->
              <article class="row align-items-stretch no-gutters bg-white rounded">
                <div class="col-md-6">
                  <div class="p-7">
                    <!-- Post Info -->
                    <ul class="list-inline small text-muted mb-1">
                      <li class="list-inline-item mr-0"><a class="text-muted" href="{% url 'blog:articles-cate' article.category.code %}">{{ article.category.name }}</a></li>
                      <li class="list-inline-item mx-2">&#8211;</li>
                      <li class="list-inline-item">{{ article.creationTime | smart_timesince:'EN' }}</li>
                    </ul>
                    <!-- End Post Info -->

                    <!-- Info -->
                    <div class="mb-4">
                      <h2 class="h5 mb-3">
                        <a href="javascript:;">{{ article.title }}</a>
                      </h2>
                      <p>{{ article.summary }}</p>
                    </div>
                    <!-- End Info -->

                    <!-- Labels -->
                    {% if article.tags %}
                        <ul class="list-inline mb-0">
                          {% for tag in article.tags.all %}
                              <li class="list-inline-item g-mb-10">
                                <a class="u-label u-label--sm u-label--danger" href="{% url 'blog:articles-tag' tag.code %}">{{ tag.name }}</a>
                              </li>
                          {% endfor %}
                        </ul>
                    {% endif %}
                    <!-- End Labels -->
                  </div>
                </div>
                <div class="col-md-6 u-bg-img-hero min-height-300 rounded" data-bg-img-src="{{ article.picture.url }}"></div>
              </article>
              <!-- End Blog Card -->
            </div>
            </div>
        <!-- End Item -->
        {% elif forloop.counter|special_article_item %}
            <!-- Item -->
          <div class="cbp-item">
            <div class="cbp-caption">
              <!-- Blog Card -->
              <article class="bg-{{ 1|random_tag_theme }} rounded text-center position-relative">
                <a class="d-block u-space-2 px-7" href="{% url 'blog:article-detail' article.id %}">
                  <!-- SVG Quote -->
                  <figure class="mx-auto mb-3" style="width: 35px;">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                       viewBox="0 0 8 8" style="enable-background:new 0 0 8 8;" xml:space="preserve">
                      <path class="u-fill-white" opacity=".7" d="M3,1.3C2,1.7,1.2,2.7,1.2,3.6c0,0.2,0,0.4,0.1,0.5c0.2-0.2,0.5-0.3,0.9-0.3c0.8,0,1.5,0.6,1.5,1.5c0,0.9-0.7,1.5-1.5,1.5
                        C1.4,6.9,1,6.6,0.7,6.1C0.4,5.6,0.3,4.9,0.3,4.5c0-1.6,0.8-2.9,2.5-3.7L3,1.3z M7.1,1.3c-1,0.4-1.8,1.4-1.8,2.3
                        c0,0.2,0,0.4,0.1,0.5c0.2-0.2,0.5-0.3,0.9-0.3c0.8,0,1.5,0.6,1.5,1.5c0,0.9-0.7,1.5-1.5,1.5c-0.7,0-1.1-0.3-1.4-0.8
                        C4.4,5.6,4.4,4.9,4.4,4.5c0-1.6,0.8-2.9,2.5-3.7L7.1,1.3z"/>
                    </svg>
                  </figure>
                  <!-- End SVG Quote -->

                  <h3 class="h4 text-white mb-4">{{ article.title }}</h3>
                  <small class="d-block u-text-light mb-1">{{ article.author.userinfo.nickname }}</small>
                </a>
              </article>
              <!-- End Blog Card -->
            </div>
          </div>
          <!-- End Item -->
        {% else %}
            <!-- Item -->
            <div class="cbp-item">
            <div class="cbp-caption">
              <!-- Blog Card -->
              <article>
                <img class="img-fluid w-100" src="{{ article.picture.url }}" alt="Image Description">

                <div class="bg-white rounded-bottom p-5">
                  <!-- Post Info -->
                  <ul class="list-inline small text-muted mb-1">
                    <li class="list-inline-item mr-0"><a class="text-muted" href="{% url 'blog:articles-cate' article.category.code %}">{{ article.category.name }}</li>
                    <li class="list-inline-item mx-2">&#8211;</li>
                    <li class="list-inline-item">{{ article.creationTime|smart_timesince:'EN' }}</li>
                  </ul>
                  <!-- End Post Info -->

                  <!-- Info -->
                  <div class="mb-4">
                    <h3 class="h5 mb-0">
                      <a href="{% url 'blog:article-detail' article.id %}">{{ article.title }}</a>
                    </h3>
                  </div>
                  <!-- End Info -->

                  <!-- Labels -->
                  <ul class="list-inline mb-0">
                      {% with themes=3|random_tag_theme %}
                          {% for tag in article.tags.all %}
                              <li class="list-inline-item g-mb-10">
                                  <a class="u-label u-label--sm u-label--{{ themes.pop }}" href="javascript:;">{{ tag.name }}</a>
                                </li>
                          {% endfor %}
                      {% endwith %}
                  </ul>
                  <!-- End Labels -->
                </div>
              </article>
              <!-- End Blog Card -->
            </div>
            </div>
        {% endif %}


{% endfor %}

blog/templates/blog/includes/logo_and_nav.html
{% load static %}
<div id="logoAndNav" class="container">
    <!-- Nav -->
    <nav class="js-mega-menu navbar navbar-expand-md u-header__navbar hs-menu-initialized hs-menu-horizontal">
        <!-- Logo -->
        {% with theme_index_logo_class='navbar-brand u-header__navbar-brand u-header__navbar-brand-top-space mr-9' theme_regular_logo_class='navbar-brand u-header__navbar-brand u-header__navbar-brand-top-space' %}
            <a class="
                    {% ifequal theme 'index' %}{{ theme_index_logo_class }}{% else %}{{ theme_regular_logo_class }}{% endifequal %}"
               href="/blog/" aria-label="Front">
                <b class="logo">JOY BLOG</b>
            </a>
        {% endwith %}
        <!-- End Logo -->

        <!-- Responsive Toggle Button -->
        <button type="button" class="navbar-toggler btn u-hamburger" aria-label="Toggle navigation"
                aria-expanded="false" aria-controls="navBar" data-toggle="collapse" data-target="#navBar">
        <span id="hamburgerTrigger" class="u-hamburger__box">
          <span class="u-hamburger__inner"></span>
        </span>
        </button>
        <!-- End Responsive Toggle Button -->

        <!-- Navigation -->
        <div id="navBar" class="collapse navbar-collapse py-0 {% ifequal theme 'index' %}ml-9{% endifequal %}">
            {% with theme_index_nav_class='navbar-nav w-100 u-header__navbar-nav' theme_regular_nav_class='navbar-nav u-header__navbar-nav ml-lg-auto' %}
                <ul class="
                        {% ifequal theme 'index' %}{{ theme_index_nav_class }}{% else %}{{ theme_regular_nav_class }}{% endifequal %}">
            {% endwith %}
            <!-- Home -->
            <li class="nav-item hs-has-mega-menu u-header__nav-item hs-mega-menu-opened"
                data-event="hover" data-animation-in="slideInUp" data-animation-out="fadeOut" data-position="left">
                <a id="homeMegaMenu" class="nav-link u-header__nav-link pl-0" href="{% url 'blog:index' %}"
                   aria-haspopup="false" aria-expanded="false">首页</a>
            </li>
            <li class="nav-item hs-has-mega-menu u-header__nav-item" data-event="hover"
                data-animation-in="slideInUp" data-animation-out="fadeOut"
                data-position="right">
                <a id="documentMegaMenu" class="nav-link u-header__nav-link" href="{% url 'blog:articles-list' %}"
                   aria-haspopup="true" aria-expanded="false">
                    发现
                </a>
            </li>
            <li class="nav-item u-header__nav-item">
                <a class="nav-link u-header__nav-link" href="{% url 'blog:topics' %}">专题</a></li>
            <li class="nav-item u-header__nav-item">
                <a class="nav-link u-header__nav-link" href="{% url 'blog:videos-lists' %}">视频</a></li>
            <li class="nav-item u-header__nav-item">
                <a class="nav-link u-header__nav-link" href="{% url 'blog:reptiles-lists' %}">爬虫</a>
            </li>
            {% if not request.user.is_anonymous %}
            {% elif theme == 'index' %}
                <li class="nav-item d-none d-md-inline-block pl-3 pr-0 ml-auto">
                    <a class="btn btn-sm btn-primary u-btn-primary transition-3d-hover" href="javascript:void(0)"
                       role="button"
                       aria-controls="sidebarContent"
                       aria-haspopup="true"
                       aria-expanded="false"
                       data-unfold-event="click"
                       data-unfold-hide-on-scroll="false"
                       data-unfold-target="#sidebarContent"
                       data-unfold-type="css-animation"
                       data-unfold-animation-in="fadeInRight"
                       data-unfold-animation-out="fadeOutRight"
                       data-unfold-duration="500">
                        登录
                    </a>
                </li>
            {% endif %}
            <!-- End Button -->
            </ul>
        </div>
        <!-- End Navigation -->
    </nav>
    <!-- End Nav -->
</div>