blog/urls.py
from django.urls import path, re_path

from blog.views import index, upload, article, comment, account, reptile, vedio, leave_messge, topic


app_name = 'blog'

urlpatterns = [
    path('', index.index, name='index'),
    path('upload/', upload.upload, name='upload'),
]

# Links about article
urlpatterns += [
    path('detail/<int:article_id>/', article.get_article_by_id, name='article-detail'),
    re_path(r'^articles/(?:page/(?P<page>\d+)/)?$', article.lists, name='articles-list'),
    re_path(r'^articles/tag/(?P<tag>\w+)/(?:page/(?P<page>\d+)/)?$', article.get_articles_by_tag, name='articles-tag'),
    re_path(r'^articles/(?P<cate>\w+)/(?:page/(?P<page>\d+)/)?$', article.get_articles_by_category, name='articles-cate'),
    path('comment/appreciate/', comment.comment_appreciate, name='comment-appreciate'),
    path('comment/dislike/', comment.comment_dislike, name='comment-dislike'),
    path('reply/dislike/', comment.reply_dislike, name='reply-dislike'),
    path('reply/appreciate/', comment.reply_appreciate, name='reply-appreciate'),
    path('reply/', comment.reply, name='article-comment'),
    path('comment/', comment.comment, name='article-comment'),
    path('comment/load_more/', comment.load_comments, name='comment-loadmore'),
]

# Links about account
urlpatterns += [
    path('user/login/', account.do_login, name='user-login'),
    path('user/logout/', account.do_logout, name='user-logout'),
    path('user/register/', account.register, name='user-register'),
    path('user/edit/', account.edit, name='user-edit'),
    path('user/do-edit/', account.do_edit, name='user-do-edit'),
    path('user/check-username/', account.check_username, name='user-check-username'),
    path('user/check-email/', account.check_email, name='user-check-email'),
    path('user/forget-password/', account.forget_password, name='user-forget-password'),
    path('user/captcha/', account.gen_captcha, name='user-gen-captcha'),
]

# Others Lnks
urlpatterns += [
    path('message/', leave_messge.leave_message, name='message-leave'),
    path('reptiles/', reptile.lists, name='reptiles-lists'),
    path('videos/', vedio.lists, name='videos-lists'),
    path('topics/', topic.lists, name='topics'),
]


blog/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Tag(models.Model):

    code = models.CharField(max_length=200, null=False, unique=True, verbose_name='编码')
    name = models.CharField(max_length=200, null=False, verbose_name='名称')
    description = models.CharField(max_length=200, null=True, verbose_name='描述')
    picture = models.ImageField(upload_to='upload/images/tag', blank=True, null=True, verbose_name='图片')
    creationTime = models.DateTimeField(null=True, default = timezone.now, verbose_name='创建时间')
    isShow = models.BooleanField(default=True, verbose_name='前台显示')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural='标签'


class FriLink(models.Model):

    url = models.CharField(max_length=200, null=False, unique=True, verbose_name='URL')
    description = models.CharField(max_length=200, null=False, verbose_name='描述')
    creationTime = models.DateTimeField(null=True, default=timezone.now, verbose_name='创建时间')
    isShow = models.BooleanField(default=True, verbose_name='前台显示')

    def __str__(self):
        return self.url

    class Meta:
        verbose_name_plural='友情链接'


class AboutMe(models.Model):

    nameEn = models.CharField(max_length=200, null=False, verbose_name='英文名')
    nameZh = models.CharField(max_length=200, null=False, verbose_name='中文名')
    headPortrait = models.ImageField(upload_to='upload/images/headPortrait', verbose_name='头像')
    job = models.CharField(max_length=200, null=False, verbose_name='工作')
    introduction = models.CharField(max_length=400, null=False, verbose_name='自我介绍')

    class Meta:
        verbose_name_plural='关于我'


class Category(models.Model):

    code = models.CharField(max_length=200, null=False, unique=True, verbose_name='类别编号')
    name = models.CharField(max_length=200, null=False, verbose_name='类别名称')
    description = models.CharField(max_length=200, null=True, verbose_name='类别描述')
    picture = models.ImageField(upload_to='upload/images/category', blank=True, verbose_name='图片')
    creationTime = models.DateTimeField(null=True, default = timezone.now, verbose_name='创建时间')
    isShow = models.BooleanField(default=True, verbose_name='前台显示')
    isSupCategory = models.BooleanField(default=False, verbose_name='是否是超类')
    supCategory = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, verbose_name='超类')

    def __str__(self):
        return self.code + '-' + self.name


    class Meta:
        verbose_name_plural = '类别'


class Article(models.Model):

    title = models.CharField(max_length=200, null=False, verbose_name='文章标题')
    author = models.ForeignKey(User, blank=False, null=True, on_delete=models.SET_NULL, verbose_name='文章作者')
    picture = models.ImageField(upload_to='upload/images/article', blank=True, verbose_name='显示图片')
    summary = models.TextField(max_length=400, null=False, verbose_name='文章摘要')
    loveTime = models.IntegerField(default=0, null=True, blank=True, editable=False, verbose_name='喜欢次数')
    viewTime = models.IntegerField(default=0, null=True, blank=True, editable=False, verbose_name='浏览次数')
    lastArticle = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True
                                    , related_name='Article_lastArticle', verbose_name='上一篇文章')
    nextArticle = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True
                                    , related_name='Article_nextArticle', verbose_name='下一篇文章')
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, blank=False, null=True, verbose_name='文章类别')
    tags = models.ManyToManyField(Tag, verbose_name='标签')
    recommend = models.BooleanField(default=False, verbose_name='是否推荐')
    highQuality = models.BooleanField(default=False, editable=False, verbose_name='是否精品')
    creationTime = models.DateTimeField(null=True, default=timezone.now, editable=False, verbose_name='发布时间')
    content = models.TextField(verbose_name='文章内容')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural='文章'


class Score(models.Model):

    LEVEL_CHOICE = (
        (0, '英勇黄铜'),
        (1, '不屈白银'),
        (2, '荣耀黄金'),
        (3, '华贵铂金'),
        (4, '璀璨钻石'),
        (5, '超凡大师'),
        (6, '最强王者')
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='用户')
    score = models.IntegerField(verbose_name='用户积分')
    level = models.IntegerField(verbose_name='用户等级', default=0, choices=LEVEL_CHOICE)

    def get_level(self):
        return self.LEVEL_CHOICE[self.level][1]

    class Meta:
        verbose_name_plural = '用户积分'


class Action(models.Model):

    DATE_TYPE_CHOICES = (
        ('Article', '文章'),
        ('Comment', '评论')
    )

    code = models.CharField(max_length=200, null=False, unique=True, verbose_name='行为编号')
    description = models.CharField(max_length=200, null=True, verbose_name='行为描述')
    worth = models.IntegerField(verbose_name='行为分')
    dateType = models.CharField(max_length=200, null=False, verbose_name='模型名称', choices=DATE_TYPE_CHOICES)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name_plural = '行为类型'


class Comment(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    article = models.ForeignKey(Article, on_delete=models.SET_NULL, blank=False, null=True, verbose_name='文章')
    creationTime = models.DateTimeField(default=timezone.now, verbose_name='评论时间')
    content = models.CharField(max_length=200, blank=False, null=False, verbose_name='评论内容')
    appreciate = models.IntegerField(default=0, verbose_name='被赞次数')
    dislike = models.IntegerField(default=0, verbose_name='被踩次数')

    class Meta:
        verbose_name_plural = '评论'


class Reply(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    article = models.ForeignKey(Article, on_delete=models.SET_NULL, blank=False, null=True, verbose_name='文章')
    creationTime = models.DateTimeField(default=timezone.now, verbose_name='评论时间')
    content = models.CharField(max_length=200, blank=False, null=False, verbose_name='评论内容')
    appreciate = models.IntegerField(default=0, verbose_name='被赞次数')
    dislike = models.IntegerField(default=0, verbose_name='被踩次数')
    comment = models.ForeignKey(Comment, blank=True, null=True, related_name='replies', on_delete=models.CASCADE, verbose_name='评论')
    reply_to = models.ForeignKey('self', blank=True, null=True, related_name='replies', on_delete=models.CASCADE, verbose_name='回复主体')

    class Meta:
        verbose_name_plural = '回复'


class Behavior(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    action = models.ForeignKey(Action, on_delete=models.CASCADE, verbose_name='行为类型')
    occurTime = models.DateTimeField(verbose_name='行为发生时间', default=timezone.now)
    relatedData = models.IntegerField(verbose_name='关联数据主键')

    def related_data(self):
        date_type_value = self.action.dateType
        if date_type_value == 'Article':
            return Article.objects.get(id=self.relatedData)
        elif date_type_value == 'Comment':
            return

    class Meta:
        verbose_name_plural = '用户行为'


class Job(models.Model):

    name = models.CharField(max_length=200, blank=True, null=True, verbose_name='职业')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '职业'


class UserInfo(models.Model):
    GENDER_CHOICES = ((1, '男'), (2, '女'), (0, '保密'))
    AVATAR_EXT_LIMITS = ('.jpg', '.jpeg', '.png')
    AVATAR_SIZE_LIMIT = 1048576
    AVATAR_SIZE_DEFAULT = (100, 100)
    EDU_CHOICES = ((1,'大专'), (2, '本科'), (3, '硕士'), (4, '博士'))
    nickname = models.CharField(max_length=200, blank=True, null=True, verbose_name='昵称', default='无名小辈')
    job = models.ForeignKey(Job, blank=True, null=True,on_delete=models.SET_NULL, verbose_name='职业')
    education = models.CharField(max_length=200, blank=True, null=True, verbose_name='学历', choices=EDU_CHOICES)
    signature = models.CharField(max_length=200, blank=True, null=True, verbose_name='签名', default='这位同学很懒，什么也没留下')
    gender = models.IntegerField(blank=True, null=True, verbose_name='性别', choices=GENDER_CHOICES, default=0)
    avatar = models.ImageField(upload_to='upload/images/avatar', blank=True, null=True, verbose_name='头像', default='upload/images/avatar/default.jpg')
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='用户')

    class Meta:
        verbose_name_plural = '用户其他信息'


class LeaveMessage(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    content = models.CharField(max_length=200, blank=True, null=True, verbose_name='留言内容')
    creationTime = models.DateTimeField(verbose_name='留言时间', default=timezone.now)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name_plural = '用户留言'



blog/views/article.py
import re

import jieba
import jieba.analyse
from django.core.cache import cache
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render
from django.views.decorators.http import require_GET

from blog.models import Article
from blog.utils.MyPaginator import MyPaginator

page_size = 10
page_width = 5


# 文章列表查询
@require_GET
def lists(request, page):
    key = request.GET.get('key')
    page = page or 1
    if key:
        return get_articles_by_key(request, page)
    else:
        articles = Article.objects.only('id', 'title', 'summary', 'picture', 'creationTime').all().order_by('-viewTime')
        p = MyPaginator(articles, page_size)
        articles = p.get_my_page(page, page_width)
        return render(request, 'blog/article/index.html', {'articles': articles})


# Article falls
@require_GET
def falls(request):
    page_num = request.GET.get('page', 1)
    page_num = page_num if page_num > 0 else 1
    articles = Article.objects.order_by('-creationTime')
    p = Paginator(articles)
    page = p.get_page(page_num)
    return render(request, 'blog/includes/falls.html', {'articles': page})


# 通过文章id获取文章详情
def get_article_by_id(request, article_id):

    article = Article.objects.filter(id=article_id).first()
    if article:

        comments = article.comment_set.all()
        comment_size = comments.count()
        reply_size = 0
        for comment in comments:
            reply_size += comment.replies.all().count()

        key = 'lock:%s:%s' % ('article', article_id)
        with cache.lock(key):
            article.viewTime += 1
            if article.viewTime > 100:
                article.recommend = True
            article.save(update_fields=['viewTime', 'recommend'])

    else:
        return None

    context = {'article': article,
               'total_num': comment_size + reply_size, 'inclusion_tag': article.tags.all()}

    return render(request, 'blog/article/detail.html', context)


# 根据标签编号查询文章
def get_articles_by_tag(request, tag, page=1):
    articles = Article.objects.filter(tags__code=tag).order_by('-viewTime')
    p = MyPaginator(articles, page_size)
    articles = p.get_my_page(page, page_width)
    return render(request, 'blog/article/index.html', {'articles': articles, 'tag': tag})


# 根据类别查询文章
def get_articles_by_category(request, cate, page=1):
    articles = Article.objects.filter(category__code=cate).order_by('-viewTime')
    p = MyPaginator(articles, page_size)
    articles = p.get_my_page(page, page_width)
    return render(request, 'blog/article/index.html', {'articles': articles, 'cate': cate})


# 根据关键词查询并分页
def get_articles_by_key(request, page):

    key = request.GET['key']

    seg_list = jieba.lcut_for_search(key, HMM=False)
    seg_list = [x for x in set(seg_list) if len(x) > 1 and re.match('[\u4e00-\u9fa5A-Za-z0-9]', x)]
    seg_list = seg_list or [key]

    query = None
    select_params_list = []
    select_dict = dict()
    order_by_title_list = []
    order_by_summary_list = []

    def contains(seg):
        return Q(title__contains=seg) | Q(summary__contains=seg)

    def title_alias(seg):
        return 'is_title_like_%s' % seg

    def summary_alias(seg):
        return 'is_summary_like_%' % seg

    def title_like(seg):
        return 'blog_article.title like %s'

    def summary_like(seg):
        return 'blog_article.summary like %s'

    #select_dict = [{title_alias(seg): title_like(seg), summary_alias(seg)} for seg in seg_list]
    for seg in seg_list:

        query = query | contains(seg) if query else contains(seg)

        title_alias = f'is_title_like_{seg}'
        summary_alias = f'is_summary_like_{seg}'
        select_dict[title_alias] = 'blog_article.title like %s'
        select_dict[summary_alias] = 'blog_article.summary like %s'
        select_params_list.append('%' + seg + '%')
        select_params_list.append('%' + seg + '%')
        order_by_title_list.append('-' + title_alias)
        order_by_summary_list.append('-' + summary_alias)

    articles = Article.objects.filter(query)\
        .only('id', 'title', 'summary', 'creationTime')\
        .extra(select=select_dict, select_params=select_params_list,
               order_by=order_by_title_list + order_by_summary_list).distinct()

    p = MyPaginator(articles, page_size)
    articles = p.get_my_page(page, page_width)

    return render(request, 'blog/article/index.html',
                  {'articles': articles, 'words': seg_list, 'key': key})

blog/views/index.py
from django.contrib.auth.models import User
from django.shortcuts import render


# index page
from blog.apps import BlogConfig
from blog.models import Article


def index(request):
    articles = Article.objects.all()
    author = User.objects.get(username=BlogConfig.author_name)
    return render(request, 'blog/index/index.html', {
        'articles': articles,
        'author': author})

blog/views/leave_messge.py
from blog.models import LeaveMessage
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import json,re


@login_required
def leave_message(request):
    """
    用户留言功能
    :param request:
    :return:
    """
    content = request.POST.get('content', None)
    if content is None:
        return HttpResponse(json.dumps({'status':False, 'message':'留言内容不能为空'}), content_type='application/json')
    elif len(re.sub(r'[^\x00-\xff]', 'aa', content)) > 60:
        return HttpResponse(json.dumps({'status': False, 'message': '留言内容太长'}), content_type='application/json')

    message = LeaveMessage()
    message.content = content
    message.user = request.user
    message.save()

    return HttpResponse(json.dumps({'status':True, 'message':'留言成功'}), content_type='application/json')

blog/views/reptile.py
from django.shortcuts import render

from blog.apps import BlogConfig
from blog.models import Article


def lists(request):
    reptiles = Article.objects.filter(tags__code=BlogConfig.reptile_tag_code).order_by('creationTime')
    return render(request, 'blog/reptile/reptiles.html', {'reptiles': reptiles})

blog/views/vedio.py
from django.shortcuts import render


def lists(request):

    return render(request, 'blog/video.html')

blog/templates/blog/tag/tags.html
{% extends 'blog/layout.html' %}
{% load static %}
{% block title %}专题页面{% endblock %}
{% block cssPlugins %}
  <!-- CSS Implementing Plugins -->
  <link rel="stylesheet" href="{% static 'blog/css/fontawesome-all.min.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/hs.megamenu.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/jquery.mCustomScrollbar.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/dzsparallaxer.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/slick.css' %}">
  <link rel="stylesheet" href="{% static 'blog/plugins/prism/prism.css' %}">
{% endblock %}
{% block main %}
  <!-- ========== MAIN ========== -->
  <main id="content" role="main">
    <!-- Blog Grid Section -->
    <div class="container u-space-4-top u-space-5-top--md u-space-4-top--lg u-space-3-bottom">
      <!-- Title -->
      <div class="w-md-80 w-lg-60 mb-9">
        <h2 class="font-weight-normal">所有专题 （<span class="text-primary font-weight-bold">{{ count }}</span>）</h2>
      </div>
      <!-- End Title -->

      {% for subtags in tags %}
            <div class="card-group d-block d-md-flex u-card--gutters-2-md">
                {% for tag in subtags %}
                    <div class="card border-0 rounded shadow-sm mb-3">
                  <!-- Blog Grid -->
                  <article class="card-body d-flex align-items-start flex-column w-100 bg-white rounded p-5">
                    <!-- Info -->
                    <small class="d-block text-muted mb-2">共{{ tag.article_set.all | length }}篇文章</small>
                    <h2 class="h5 text-center">
                      <a href="#">InVision design forward fund</a>
                    </h2>
                    <p class="text-center">{{ tag.description }}</p>
                    <!-- End Info -->

                    <div class="w-100 mt-auto">
                      <hr>
                      <!-- Author -->
                      <div class="media">
                        <div class="d-flex mr-3">
                          <img class="u-sm-avatar rounded-circle" src="{{ tag.picture.url }}" alt="Image Description">
                        </div>
                        <div class="media-body">
                          <h4 class="d-inline-block mb-0">
                            <a class="d-block font-size-13" href="">{{ tag.name }}</a>
                          </h4>
                        </div>
                      </div>
                      <!-- End Author -->
                    </div>
                  </article>
                  <!-- End Blog Grid -->
                </div>
                {% endfor %}
            </div>
      {% endfor %}


      <div class="u-space-2-bottom"></div>

      <!-- End Pagination -->
    </div>
    <!-- End Blog Grid Section -->

    <!-- Sticky Block End Point -->
    <div id="stickyBlockEndPoint"></div>

    <!-- Subscribe Section -->
    <div class="position-relative u-gradient-half-primary-v1 u-space-3-top u-space-4-bottom">
      <div class="container">
        <div class="row justify-content-md-center">
          <div class="col-md-9 col-lg-7 col-xl-6 offset-xl-2">
            <!-- Title -->
            <div class="text-center mb-4">
              <span class="u-label u-label--sm u-label--white mb-2">Subscribe</span>
              <h2 class="h1 text-white"><span class="font-weight-bold">Stay</span> in the know</h2>
              <p class="lead u-text-light">Get special offers on the latest developments from Front.</p>
            </div>
            <!-- End Title -->

            <!-- Form -->
            <form class="js-validate js-form-message mb-2" novalidate="novalidate">
              <div class="js-focus-state input-group input-group-lg u-form u-form--lg u-form--white-brd">
                <input type="email" class="form-control u-form__input" name="email" required="" placeholder="Enter your email address" aria-label="Enter your email address" data-msg="Please enter a valid email address." data-error-class="u-has-error" data-success-class="u-has-success">
                <div class="input-group-append u-form__append">
                  <button type="submit" class="btn btn-warning u-btn-wide">Join Front</button>
                </div>
              </div>
            </form>
            <!-- End Form -->

            <!-- Info -->
            <div class="d-block d-xl-none">
              <p class="small u-text-light mb-0">Be the lucky user to earn <span class="text-white font-weight-bold">$1000</span> bonus now!</p>
            </div>
            <!-- End Info -->
          </div>

          <div class="col-xl-2 d-none d-xl-inline-block mt-auto mb-7">
            <div class="position-relative p-3">
              <p class="small u-text-light mb-0">Be the lucky user to earn <span class="text-white font-weight-bold">$1000</span> bonus now!</p>

              <!-- SVG Shape -->
              <figure class="position-absolute-top-0">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 254 204.2" style="enable-background:new 0 0 254 204.2;" xml:space="preserve">
                  <path class="u-fill-none u-stroke-white" opacity=".5" stroke-width="2" stroke-miterlimit="10" stroke-dasharray="10" d="M0.5,171V6.5c0-3.3,3.3-6,7.3-6h238.6c3.9,0,7.1,2.6,7.1,5.8v164c0,3.6-3.5,6.5-7.9,6.5H61.4
                    c-3,0-5.6,1.4-6.8,3.7l-22,22.6l-0.2-22.4c-1.1-2.3-3.8-3.9-6.8-3.9H7.6C3.7,176.8,0.5,174.2,0.5,171z"></path>
                </svg>
              </figure>
              <!-- End SVG Shape -->
            </div>
          </div>
        </div>
      </div>

      <!-- SVG Phone Mockup -->
      <div class="d-none d-lg-block u-devices-v2__phone u-devices-v2__phone--left-position">
        <figure class="w-75 u-devices-v2__phone-svg">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 317.5 665" style="enable-background:new 0 0 317.5 665;" xml:space="preserve">
            <path class="u-fill-white" d="M263,666H54c-29.7,0-54-24.3-54-54V55C0,25.3,24.3,1,54,1h209c29.7,0,54,24.3,54,54v557
              C317,641.7,292.7,666,263,666z"></path>
            <circle class="u-fill-gray-75" cx="159.5" cy="619.5" r="25.5"></circle>
            <path class="u-fill-gray-75" fill-rule="evenodd" clip-rule="evenodd" d="M180,52h-42c-2.2,0-4-1.8-4-4v0c0-2.2,1.8-4,4-4h42c2.2,0,4,1.8,4,4v0C184,50.2,182.2,52,180,52z"></path>
            <g>
              <defs>
                <rect id="phoneFrameID1" x="19.4" y="81.3" width="280" height="500"></rect>
              </defs>
              <clippath id="phoneFrameID2">
                <use xlink:href="#phoneFrameID1" style="overflow:visible;"></use>
              </clippath>
              <g style="clip-path:url(#phoneFrameID2);">
                <!-- Apply your (282px width to 500px height) image here -->
                <image style="overflow:visible;" width="282" height="500" xlink:href="../../assets/img/282x500/img3.jpg" transform="matrix(1 0 0 1 18 81)"></image>
              </g>
              <use class="u-fill-none u-stroke-light-blue-125" xlink:href="#phoneFrameID1" stroke-miterlimit="10" style="overflow: visible;"></use>
            </g>
          </svg>
        </figure>
      </div>
      <!-- End SVG Phone Mockup -->
    </div>
    <!-- End Subscribe Section -->

    <!-- SVG Background -->
    <figure class="position-absolute-bottom-0 z-index-2">
      <svg preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100%" height="140px" viewBox="20 -20 300 100" style="margin-bottom: -8px;" xml:space="preserve">
        <path class="u-fill-white" opacity="0.4" d="M30.913,43.944c0,0,42.911-34.464,87.51-14.191c77.31,35.14,113.304-1.952,146.638-4.729
    c48.654-4.056,69.94,16.218,69.94,16.218v54.396H30.913V43.944z"></path>
        <path class="u-fill-white" opacity="0.4" d="M-35.667,44.628c0,0,42.91-34.463,87.51-14.191c77.31,35.141,113.304-1.952,146.639-4.729
    c48.653-4.055,69.939,16.218,69.939,16.218v54.396H-35.667V44.628z"></path>
        <path class="u-fill-white" opacity="0" d="M43.415,98.342c0,0,48.283-68.927,109.133-68.927c65.886,0,97.983,67.914,97.983,67.914v3.716
    H42.401L43.415,98.342z"></path>
        <path class="u-fill-white" d="M-34.667,62.998c0,0,56-45.667,120.316-27.839C167.484,57.842,197,41.332,232.286,30.428
    c53.07-16.399,104.047,36.903,104.047,36.903l1.333,36.667l-372-2.954L-34.667,62.998z"></path>
      </svg>
    </figure>
    <!-- End SVG Background Section -->
  </main>
  <!-- ========== END MAIN ========== -->
{% endblock %}