blog/urls.py
from django.urls import path, re_path

from blog.views import index, upload, article, comment, account, reptile, vedio, leave_messge, topic


app_name = 'blog'

urlpatterns = [
    path('', index.index, name='index'),
    path('upload/', upload.upload, name='upload'),
]

# Links about article
urlpatterns += [
    path('detail/<int:article_id>/', article.get_article_by_id, name='article-detail'),
    re_path(r'^articles/(?:page/(?P<page>\d+)/)?$', article.lists, name='articles-list'),
    re_path(r'^articles/tag/(?P<tag>\w+)/(?:page/(?P<page>\d+)/)?$', article.get_articles_by_tag, name='articles-tag'),
    re_path(r'^articles/(?P<cate>\w+)/(?:page/(?P<page>\d+)/)?$', article.get_articles_by_category, name='articles-cate'),
    path('comment/appreciate/', comment.comment_appreciate, name='comment-appreciate'),
    path('comment/dislike/', comment.comment_dislike, name='comment-dislike'),
    path('reply/dislike/', comment.reply_dislike, name='reply-dislike'),
    path('reply/appreciate/', comment.reply_appreciate, name='reply-appreciate'),
    path('reply/', comment.reply, name='article-comment'),
    path('comment/', comment.comment, name='article-comment'),
    path('comment/load_more/', comment.load_comments, name='comment-loadmore'),
]

# Links about account
urlpatterns += [
    path('user/login/', account.do_login, name='user-login'),
    path('user/logout/', account.do_logout, name='user-logout'),
    path('user/register/', account.register, name='user-register'),
    path('user/edit/', account.edit, name='user-edit'),
    path('user/do-edit/', account.do_edit, name='user-do-edit'),
    path('user/check-username/', account.check_username, name='user-check-username'),
    path('user/check-email/', account.check_email, name='user-check-email'),
    path('user/forget-password/', account.forget_password, name='user-forget-password'),
    path('user/captcha/', account.gen_captcha, name='user-gen-captcha'),
]

# Others Lnks
urlpatterns += [
    path('message/', leave_messge.leave_message, name='message-leave'),
    path('reptiles/', reptile.lists, name='reptiles-lists'),
    path('videos/', vedio.lists, name='videos-lists'),
    path('topics/', topic.lists, name='topics'),
]


blog/views/account.py
import base64
import os
import re
import uuid
from functools import partial

from PIL import Image
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.cache import cache
from django.core.files.base import ContentFile
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.utils import timezone
from django.views.decorators.http import require_GET, require_POST

from blog.models import UserInfo, Job
from blog.utils.http import (JsonSuccessResponse,
                             JsonFailResponse)
from blog.utils.thread_email import send_mail
from blog.views import captcha
from blogproject import settings

send_forget_password_mail = partial(send_mail, '密码找回邮件确认', '', '1147883997@qq.com')

EMAIL_PATTERN = r'^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,})$'


@require_POST
def do_login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    if not username or not password:
        return JsonFailResponse('username or password is null')

    user = User.objects.filter(Q(username=username) | Q(email=username)).first()
    if not user or not user.check_password(password):
        return JsonFailResponse('username or password is wrong')

    login(request, user)
    return JsonSuccessResponse('login success')


@require_POST
def register(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    if not username or not password:
        return JsonFailResponse('username or password is null')

    try:
        user = User.objects.create_user(request.POST['username'], '', request.POST['password'])
        user.save()
    except Exception as e:
        print(e)
        return JsonFailResponse('create user failed')
    else:
        user_info = UserInfo()
        user_info.user = user
        user_info.save()
        login(request, user)

    return JsonSuccessResponse('register success')


def is_login(request):
    return not request.user.is_anonymous


@login_required
def do_logout(request):
    logout(request)
    return HttpResponseRedirect('/blog/articles/')


@login_required
def edit(request):
    return render(request, 'blog/account/profile_edit.html')


@require_POST
@login_required
def do_edit(request):
    nickname = request.POST.get('nickname')
    email = request.POST.get('email')
    signature = request.POST.get('signature')
    gender = request.POST.get('gender')
    job = request.POST.get('job')
    education = request.POST.get('education')
    f_avatar = request.FILES.get('avatar')

    user_info = request.user.userinfo or UserInfo()
    if not nickname or len(nickname) > 50:
        return JsonFailResponse('username is null or too long')
    user_info.nickname = nickname

    if not email or not re.match(EMAIL_PATTERN, email) or email_exists(request):
        return JsonFailResponse('invalid email')
    request.user.email = email

    if signature:
        user_info.signature = signature

    if gender:
        if int(gender) in [i[0] for i in UserInfo.GENDER_CHOICES]:
            user_info.gender = gender
        else:
            return JsonFailResponse('invalid gender')

    if job:
        user_info.job = Job.objects.get(id=job)

    if education:
        user_info.education = education

    if f_avatar:
        ext = os.path.splitext(f_avatar.name)[1]
        if ext not in UserInfo.AVATAR_EXT_LIMITS:
            return JsonFailResponse(f'unsupported ext {ext}')

        if f_avatar.size > UserInfo.AVATAR_SIZE_LIMIT:
            return JsonFailResponse(f'image size is too big')

        f_avatar_con = ContentFile(f_avatar.read())
        f_avatar_name = request.user.username + ext
        user_info.avatar.save(f_avatar_name, f_avatar_con, save=False)

        img = Image.open(os.path.join(settings.MEDIA_ROOT, 'upload', 'images', 'avatar', f_avatar_name))
        out = img.resize(UserInfo.AVATAR_SIZE_DEFAULT, resample=Image.ANTIALIAS)
        out.save(f_avatar_name)

    user_info.save()

    return JsonSuccessResponse('edit success')


def email_exists(request):
    email = request.GET.get('email')
    user = User.objects.filter(email=email).first()
    return user and (request.user.is_authenticated or request.user != user)


@require_GET
def check_username(request):
    username = request.GET.get('username')
    user = User.objects.filter(username=username).first()
    return JsonResponse({'valid': user is None or user == request.user})


@require_GET
def check_email(request):
    return JsonResponse({'valid': not email_exists(request)})


@require_GET
def gen_captcha(request):
    data, code = captcha.draw(font_size=40)
    request.session['{sessionid}_captcha'.format(sessionid=request.COOKIES.get('sessionid'))] = code.upper()
    return HttpResponse(data)


@require_POST
def forget_password(request):
    email = request.POST.get('email')
    captcha_ = request.POST.get('captcha')
    sessionid = request.COOKIES.get('sessionid')
    session_captcha = request.session.get(f'{sessionid}_captcha')

    if not email or not captcha_:
        return JsonFailResponse('email or captcha is null')

    if captcha_.upper() != session_captcha:
        return JsonFailResponse('invalid captcha')

    try:
        send_forget_password_mail(
            [email],
            html_message="""
                Dear JoyBlog user! <br><br><br>
                When you visit JoyBlog, you click the "forget password" link, which is a password reset confirmation message. <br><br>
                You can reset the account password by clicking the following link: <br><br>
                <a href= "target=" target= "_blank" > click on the link to retrieve the password<br>
                To keep your account safe, click on the link within 10 minutes, or you can copy the link to the browser's address bar. <br>
                If you have not tried to modify the password, please ignore this email, and this will inconvenience you. <br><br><br>
                This email is automatically sent by the system, please do not reply directly.
                """
        )
    except BaseException as e:
        print(e)
        return JsonFailResponse('email send failed')
    else:
        key = f'forget_password:{email}'
        value = {
            'uuid_str': base64.b64encode(uuid.uuid4().hex.encode('utf-8')),
            'link_id': base64.b64encode(str(timezone.now().timestamp()).encode('utf-8'))
        }
        cache.set(key, value, timeout=60 * 10)
        return JsonSuccessResponse('email send success')

blog/views/article.py
import re

import jieba
import jieba.analyse
from django.core.cache import cache
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render
from django.views.decorators.http import require_GET

from blog.models import Article
from blog.utils.MyPaginator import MyPaginator

page_size = 10
page_width = 5


# 文章列表查询
@require_GET
def lists(request, page):
    key = request.GET.get('key')
    page = page or 1
    if key:
        return get_articles_by_key(request, page)
    else:
        articles = Article.objects.only('id', 'title', 'summary', 'picture', 'creationTime').all().order_by('-viewTime')
        p = MyPaginator(articles, page_size)
        articles = p.get_my_page(page, page_width)
        return render(request, 'blog/article/index.html', {'articles': articles})


# Article falls
@require_GET
def falls(request):
    page_num = request.GET.get('page', 1)
    page_num = page_num if page_num > 0 else 1
    articles = Article.objects.order_by('-creationTime')
    p = Paginator(articles)
    page = p.get_page(page_num)
    return render(request, 'blog/includes/falls.html', {'articles': page})


# 通过文章id获取文章详情
def get_article_by_id(request, article_id):

    article = Article.objects.filter(id=article_id).first()
    if article:

        comments = article.comment_set.all()
        comment_size = comments.count()
        reply_size = 0
        for comment in comments:
            reply_size += comment.replies.all().count()

        key = 'lock:%s:%s' % ('article', article_id)
        with cache.lock(key):
            article.viewTime += 1
            if article.viewTime > 100:
                article.recommend = True
            article.save(update_fields=['viewTime', 'recommend'])

    else:
        return None

    context = {'article': article,
               'total_num': comment_size + reply_size, 'inclusion_tag': article.tags.all()}

    return render(request, 'blog/article/detail.html', context)


# 根据标签编号查询文章
def get_articles_by_tag(request, tag, page=1):
    articles = Article.objects.filter(tags__code=tag).order_by('-viewTime')
    p = MyPaginator(articles, page_size)
    articles = p.get_my_page(page, page_width)
    return render(request, 'blog/article/index.html', {'articles': articles, 'tag': tag})


# 根据类别查询文章
def get_articles_by_category(request, cate, page=1):
    articles = Article.objects.filter(category__code=cate).order_by('-viewTime')
    p = MyPaginator(articles, page_size)
    articles = p.get_my_page(page, page_width)
    return render(request, 'blog/article/index.html', {'articles': articles, 'cate': cate})


# 根据关键词查询并分页
def get_articles_by_key(request, page):

    key = request.GET['key']

    seg_list = jieba.lcut_for_search(key, HMM=False)
    seg_list = [x for x in set(seg_list) if len(x) > 1 and re.match('[\u4e00-\u9fa5A-Za-z0-9]', x)]
    seg_list = seg_list or [key]

    query = None
    select_params_list = []
    select_dict = dict()
    order_by_title_list = []
    order_by_summary_list = []

    def contains(seg):
        return Q(title__contains=seg) | Q(summary__contains=seg)

    def title_alias(seg):
        return 'is_title_like_%s' % seg

    def summary_alias(seg):
        return 'is_summary_like_%' % seg

    def title_like(seg):
        return 'blog_article.title like %s'

    def summary_like(seg):
        return 'blog_article.summary like %s'

    #select_dict = [{title_alias(seg): title_like(seg), summary_alias(seg)} for seg in seg_list]
    for seg in seg_list:

        query = query | contains(seg) if query else contains(seg)

        title_alias = f'is_title_like_{seg}'
        summary_alias = f'is_summary_like_{seg}'
        select_dict[title_alias] = 'blog_article.title like %s'
        select_dict[summary_alias] = 'blog_article.summary like %s'
        select_params_list.append('%' + seg + '%')
        select_params_list.append('%' + seg + '%')
        order_by_title_list.append('-' + title_alias)
        order_by_summary_list.append('-' + summary_alias)

    articles = Article.objects.filter(query)\
        .only('id', 'title', 'summary', 'creationTime')\
        .extra(select=select_dict, select_params=select_params_list,
               order_by=order_by_title_list + order_by_summary_list).distinct()

    p = MyPaginator(articles, page_size)
    articles = p.get_my_page(page, page_width)

    return render(request, 'blog/article/index.html',
                  {'articles': articles, 'words': seg_list, 'key': key})

blog/views/captcha.py
import random, math
from io import BytesIO
from PIL import Image, ImageDraw, ImageFont


def _random_bg_color():
    """获取随机的背景颜色"""
    return random.randint(50, 250), random.randint(50, 255), random.randint(50, 255)


def _random_font_color():
    """获取随机的字体颜色"""
    return random.randint(200, 255), random.randint(0, 50), random.randint(0, 50)


def _random_line_point_color():
    """生成随机颜色"""
    return random.randint(0, 255), random.randint(10, 255), random.randint(64, 255)


def _random_char():
    """获取随机字符"""
    return random.choice([chr(random.randint(65, 90)), str(random.randint(1, 9)), chr(random.randint(97, 122))])


def _char_pos(index, length, size, font_size):
    """
    获取字符的插入点
    :param index: 字符的下标
    :param length: 验证码长度
    :param size: 验证码图片尺寸(width, height)
    :param font_size: 字体大小
    :return:
    """
    width, height = size
    grid_width = math.ceil(width / length)
    return random.randint(grid_width * index, grid_width * (index+1) - font_size), random.randint(0, height-font_size)


def draw(width=279, height=50, length=6, font_file='AaDongRiGuShi-2.ttf', font_size=30):
    """
    绘制验证码图片
    :param width: 图片宽度
    :param height: 图片高度
    :param length: 字符长度
    :param font_file: 字体文件
    :param font_size: 字体大小
    :return: data图片, code验证码
    """
    f = BytesIO()
    font = ImageFont.truetype('blog/static/blog/webfonts/captcha/' + font_file, font_size)

    img = Image.new(mode='RGB', size=(width, height), color=_random_bg_color())
    draw = ImageDraw.Draw(img, mode='RGB')

    char_list = []

    # 画字
    for i in range(length):
        char = _random_char()
        print('='*20, _char_pos(i, length, (width, height), font_size))
        draw.text(_char_pos(i, length, (width, height), font_size), char, _random_font_color(), font=font)
        char_list.append(char)

    # 写干扰点
    for i in range(40):
        draw.point([random.randint(0, width), random.randint(0, height)], fill=_random_line_point_color())

    # 写干扰圆圈
    for i in range(40):
        draw.point([random.randint(0, width), random.randint(0, height)], fill=_random_line_point_color())
        x = random.randint(0, width)
        y = random.randint(0, height)
        draw.arc((x, y, x + 4, y + 4), 0, 90, fill=_random_line_point_color())

    # 画干扰线
    for i in range(5):
        x1 = random.randint(0, width)
        y1 = random.randint(0, height)
        x2 = random.randint(0, width)
        y2 = random.randint(0, height)
        draw.line((x1, y1, x2, y2), fill=_random_line_point_color())

    img.save(f, "png")
    return f.getvalue(), ''.join(char_list)

blog/views/index.py
from django.contrib.auth.models import User
from django.shortcuts import render


# index page
from blog.apps import BlogConfig
from blog.models import Article


def index(request):
    articles = Article.objects.all()
    author = User.objects.get(username=BlogConfig.author_name)
    return render(request, 'blog/index/index.html', {
        'articles': articles,
        'author': author})

blog/views/leave_messge.py
from blog.models import LeaveMessage
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import json,re


@login_required
def leave_message(request):
    """
    用户留言功能
    :param request:
    :return:
    """
    content = request.POST.get('content', None)
    if content is None:
        return HttpResponse(json.dumps({'status':False, 'message':'留言内容不能为空'}), content_type='application/json')
    elif len(re.sub(r'[^\x00-\xff]', 'aa', content)) > 60:
        return HttpResponse(json.dumps({'status': False, 'message': '留言内容太长'}), content_type='application/json')

    message = LeaveMessage()
    message.content = content
    message.user = request.user
    message.save()

    return HttpResponse(json.dumps({'status':True, 'message':'留言成功'}), content_type='application/json')

blog/views/reptile.py
from django.shortcuts import render

from blog.apps import BlogConfig
from blog.models import Article


def lists(request):
    reptiles = Article.objects.filter(tags__code=BlogConfig.reptile_tag_code).order_by('creationTime')
    return render(request, 'blog/reptile/reptiles.html', {'reptiles': reptiles})

blog/views/vedio.py
from django.shortcuts import render


def lists(request):

    return render(request, 'blog/video.html')

blog/templates/blog/account/edit.html
{% extends 'blog/site.html' %}
{% load static %}
{% block title %}个人设置{% endblock %}
{% block cssPlugins %}
          <!-- CSS Implementing Plugins -->
  <link rel="stylesheet" href="{% static 'blog/css/fontawesome-all.min.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/hs.megamenu.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/jquery.mCustomScrollbar.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/dzsparallaxer.css' %}">
{% endblock %}
{% block main %}
      <!-- ========== MAIN ========== -->
  <main id="content" role="main">
    <!-- Hero Section -->
    <div class="dzsparallaxer auto-init height-is-based-on-content use-loading mode-scroll animation-engine-js loaded dzsprx-readyall" data-options="{direction: &quot;normal&quot;}">
      <!-- Apply your Parallax background image here -->
      <div class="divimage dzsparallaxer--target" style="height: 120%; background-image: url('{% static 'blog/images/1920x1080/img1.jpg' %}'); transform: translate3d(0px, -101.484px, 0px);"></div>

      <!-- Content -->
      <div class="container position-relative u-space-5-top u-space-3-bottom z-index-2">
        <div class="w-lg-80 text-center mx-auto">
          <h1 class="display-3 font-size-48--md-down text-white font-weight-bold">个人设置</h1>
          <p class="lead text-white">我们不会涉及您的隐私，只是想让您有更好的体验.</p>
        </div>
      </div>
      <!-- End Content -->
    </div>
    <!-- End Hero Section -->

    <hr class="my-0">

    <!-- Contact Form Section -->
    <div class="container u-space-2">
      <!-- Title -->
      <div class="w-md-80 w-lg-60 text-center mx-auto mb-0">
        <span class="btn-tips u-label u-label--sm u-label--success mb-2">温馨提示</span>
        <div class="tips">
            <h2 class="text-primary font-weight-normal">完善下面的信息，有哪些好处？</h2>
            <p><b class="text-underline">昵称</b>会在评论和回复中显示，如果您没有昵称，默认显示<b>无名小辈</b>：）.</p>
            <p>如果您绑定了<b class="text-underline">邮箱</b>，您可以使用邮箱登录，并且当您有新的回复时，我们也会邮件通知您.</p>
            <p>上传您的个性<b class="text-underline">头像</b>，会让别人对你印象深刻，否则将使用默认头像.</p>
            <p><b class="text-danger">请您注意</b>：您上传的头像图片尺寸最终会被截取为<b class="text-underline">100×100</b>，为了能正常显示，请上传尺寸大于或等于100×100，且图片不能大于<b class="text-underline">1M.</b></p>
        </div>
      </div>

      <!-- End Title -->
        
      <div class="w-lg-80 mx-auto">

        <div class="alert alert-success alert-dismissible fade" role="alert">
          <strong>修改成功!</strong>.
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <!-- Contacts Form -->
        <form id="editForm" class="js-validate" action="{% url 'blog:user-do-edit' %}" method="post" enctype="multipart/form-data" novalidate="novalidate">
            {% csrf_token %}
          <div class="row">
            <!-- Input -->
            <div class="col-sm-6 mb-6">
              <div class="js-form-message">
                <label class="h6 small d-block text-uppercase">
                  昵称
                  <span class="text-danger">*</span>
                </label>

                <div class="js-focus-state input-group u-form">
                  <input class="form-control u-form__input" type="text" name="nickname" value="{{ request.user.userinfo.nickname }}" required data-rule-maxlength="50"
                         placeholder="请输入昵称" aria-label="" data-msg="昵称不能为空." data-msg-maxlength="昵称的长度不能超过50个字符."
                         data-error-class="u-has-error" data-success-class="u-has-success">
                </div>
              </div>
            </div>
            <!-- End Input -->

            <!-- Input -->
            <div class="col-sm-6 mb-6">
              <div class="js-form-message">
                <label class="h6 small d-block text-uppercase">
                  邮箱地址
                  <span class="text-danger">*</span>
                </label>

                <div class="js-focus-state input-group u-form">
                  <input class="form-control u-form__input" type="email" name="email" value="{{ request.user.userinfo.email }}" required placeholder="请输入您的邮箱"
                         aria-label="" data-msg="邮箱地址不能为空." data-msg-email="请输入正确的邮箱地址." data-error-class="u-has-error" data-success-class="u-has-success">
                </div>
              </div>
            </div>
            <!-- End Input -->

            <div class="w-100"></div>

            <!-- Input -->
            <div class="col-sm-6 mb-6">
              <div class="js-form-message">
                <label class="h6 small d-block text-uppercase">
                  头像
                </label>

                <div class="js-focus-state input-group u-form">
                  <input class="form-control u-form__input" type="text" name="avatar_text" placeholder="点击上传头像(.jpg, .jpeg, .png)" readonly aria-label="avatar"
                         onclick="avatar.click()"/>
                  <input type="file" name="avatar" accept="image/jpeg,image/png" style="display: none" onchange="avatar_text.value=this.value"/>
                </div>
              </div>
            </div>
            <!-- End Input -->

            <!-- Input -->
            <div class="col-sm-6 mb-6">
              <div class="js-form-message">
                <label class="h6 small d-block text-uppercase">
                  职业
                </label>

                <div class="js-focus-state input-group u-form">
                  <select class="form-control" name="job">
                      <option>请选择职业</option>
                      <option>WEB开发工程师</option>
                  </select>
                </div>
              </div>
            </div>
            <!-- End Input -->

                       <!-- Input -->
            <div class="col-sm-6 mb-6">
              <div class="js-form-message">
                <label class="h6 small d-block text-uppercase">
                  学历
                </label>

                <div class="js-focus-state input-group u-form">
                  <select class="form-control" name="education">
                      <option>请选择学历</option>
                      <option>大专</option>
                      <option>本科</option>
                      <option>硕士</option>
                      <option>博士</option>
                  </select>
                </div>
              </div>
            </div>
            <!-- End Input -->

            <!-- Input -->
            <div class="col-sm-6 mb-6">
              <div class="js-form-message">
                <label class="h6 small d-block text-uppercase">
                  性别
                  <span class="text-danger">*</span>
                </label>

                <div class="input-group form-control-plaintext">
                    <div class="js-focus-state u-form form-check form-check-inline">
                  <input class="form-check-input" type="radio" id="male" name="gender" value="1" data-error-class="u-has-error" data-success-class="u-has-success" {% ifequal request.user.userinfo.gender 1 %}checked{% endifequal %}>
                  <label class="form-check-label" for="male">男</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" id="female" name="gender" value="2" data-error-class="u-has-error" data-success-class="u-has-success" {% ifequal request.user.userinfo.gender 2 %}checked{% endifequal %}>
                  <label class="form-check-label" for="female">女</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" id="secret" name="gender" value="0" data-error-class="u-has-error" data-success-class="u-has-success" {% ifequal request.user.userinfo.gender 0 %}checked{% endifequal %}>
                  <label class="form-check-label" for="female">保密</label>
                </div>
                </div>

              </div>
            </div>
            <!-- End Input -->
          </div>

          <!-- Input -->
          <div class="js-form-message mb-9">
            <label class="h6 small d-block text-uppercase">
              个性签名
            </label>

            <div class="input-group u-form">
              <textarea class="form-control u-form__input" rows="4" name="signature" value="{{ request.user.userinfo.signature }}" placeholder="请输入您的个性签名..." aria-label="" data-msg="输入您的签名" data-error-class="u-has-error" data-success-class="u-has-success"></textarea>
            </div>
          </div>
          <!-- End Input -->

          <div class="text-center">
            <button type="button" class="btn btn-primary u-btn-primary u-btn-wide transition-3d-hover mb-4">提交</button>
          </div>
        </form>
        <!-- End Contacts Form -->
      </div>
    </div>
    <!-- End Contact Form Section -->

  </main>
  <!-- ========== END MAIN ========== -->
{% endblock %}
{% block jsPlugins %}
  <!-- JS Implementing Plugins -->
  <script src="{% static 'blog/js/hs.megamenu.js' %}"></script>
  <script src="{% static 'blog/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
  <script src="{% static 'blog/js/jquery.validate.min.js' %}"></script>
{% endblock %}

{% block pageScripts %}
  <!-- JS Plugins Init. -->
  <script>
    $(window).on('load', function () {
      // initialization of HSMegaMenu component
      $('.js-mega-menu').HSMegaMenu({
        event: 'hover',
        pageContainer: $('.container'),
        breakpoint: 768,
        hideTimeOut: 0
      });
    });

    $(document).on('ready', function () {
      // initialization of header
      $.HSCore.components.HSHeader.init($('#header'));

      // initialization of malihu scrollbar
      $.HSCore.components.HSMalihuScrollBar.init($('.js-scrollbar'));

      // initialization of show animations
      $.HSCore.components.HSShowAnimation.init('.js-animation-link');

      // 表单提交验证
      $.HSCore.components.HSValidation.init('.js-validate');

      // initialization of forms
      $.HSCore.helpers.HSFocusState.init();

      // initialization of go to
      $.HSCore.components.HSGoTo.init('.js-go-to');
    });

    // initialization of google map
    function initMap() {
      $.HSCore.components.HSGMap.init('.js-g-map');
      $.HSCore.components.HSGMap.init('#gMapMultipleMarkers', {
        infoWindowTemplate: function (imgsrc, imgalt, date, locationname, title) {
          return '<div class="u-gmap-v1__info">' +
            '<img class="img-fluid mb-2" src="' + imgsrc + '" alt="' + imgalt + '">' +
            '<small class="d-block text-muted mb-2">' + date + '</small>' +
            '<h4 class="h6 mb-0">' + title + '</h4>' +
            '<p class="mb-0">' + locationname + '</p>' +
            '</div>';
        }
      });
    }

    $('.tips').hide();
    $('.btn-tips').click(function () {
        $('.tips').toggle();
    });
  </script>
    <script src="{% static 'blog/js/jb.user-edit-form.js' %}"></script>
{% endblock %}